spring:
  profiles:
    active: local
#  webflux:
#    static-path-pattern: "/**"
#  resources:
#    static-locations: "classpath:/resources/"

server:
  port: 8187

process: "akka.tcp://ActorSystem@127.0.0.1:12553/user/master"
